name: C/C++ CI

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
      - test

jobs:
  build_ubuntu_latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd spc2_pack; g++ --version; make

  build_windows_latest:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd spc2_pack; g++ --version; make
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: spc2_pack
        path: ${{ github.workspace }}/spc2_pack/*.exe

  build_macos_latest:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd spc2_pack; g++ --version; make
